FROM node:22-alpine

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN apk add --no-cache python3 make g++ \
  && pnpm install --frozen-lockfile

COPY . .

EXPOSE 3201

CMD ["pnpm", "start"]
